imports:
    - php

tools:
    external_code_coverage:
        timeout: 7200 # Timeout in seconds: 2 hours

build:
  nodes:
    analysis:
      environment:
        php:
          version: 8.3
      tests:
        override:
          - php-scrutinizer-run